apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-springboot
spec:
  template:
    spec:
      containers:
      - image: gooner4life/knative-springboot:v1
        env:
        - name: version
          value: v2
        livenessProbe:
          httpGet:
            path: /liveness
        readinessProbe:
          httpGet:
            path: /readiness
  traffic:
  - tag: v1
    revisionName: knative-springboot-v1
    percent: 80
  - tag: v2
    revisionName: knative-springboot-v2
    percent: 20
