apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-springboot
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: gooner4life/knative-springboot:v1
        livenessProbe:
          httpGet:
            path: /health/live
        readinessProbe:
          httpGet:
            path: /health/ready


